image: gitpod/workspace-full

tasks:
  - name: Start PHP Server
    init: |
      sudo apt update
      sudo apt install -y php unzip
    command: |
      php -S 0.0.0.0:3000 -t .

ports:
  - port: 3000
    onOpen: open-preview
